services:
  db:
    image: postgres:18.0
    restart: unless-stopped
    environment:
      - POSTGRES_USER=yukine
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - POSTGRES_DB=db
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U yukine -d db']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  pg_data:
